# PARKED — WMP 7.1. Not in the OSD list (menu=0). Filename is historical.

[osd]
index=
menu=0
experimental=1
parked=1

[app]
name=Windows Media Player 9 (parked)
exe=C:\Program Files\Windows Media Player\wmplayer.exe
unix_exe=/media/fat/games/WinEXE/wineprefix-prebuilt/drive_c/Program Files/Windows Media Player/wmplayer.exe
workdir=
args=
explorer=1
desktop=ss1,640x480
require=/media/fat/games/WinEXE/wineprefix-prebuilt/drive_c/Program Files/Windows Media Player/wmplayer.exe

[runtime]
box86=/media/fat/games/WinEXE/box86-ss1/box86-gstflow
wine_prefix=/media/fat/games/WinEXE/wineprefix-prebuilt

[env]
WINEDLLOVERRIDES=winemenubuilder.exe=d
WINEDEBUG=+err

[display]
presenter_hz=60
skip_unchanged=1
dirty=0
tile_w=32
tile_h=32
dirty_pct=60
fb_format=auto
xsetroot=#000000

[cpu]
app_affinity=
presenter_affinity=0x3
xorg_affinity=0x3
app_comm=

[helpers]
pre=
post=
background=
cleanup=

[config]
registry=
script=
