#!/bin/sh
# Box86 + wineserver wrapper. Installed as /media/fat/games/WinEXE/bin/wineserver
WIN="${WIN:-/media/fat/games/WinEXE}"
BOX86="${BOX86:-$WIN/box86-ss1/box86}"
WS="${WINESERVER:-$WIN/wine-installer/opt/wine-devel/bin/wineserver}"
export BOX86_NOBANNER="${BOX86_NOBANNER:-1}"
if [ -z "${BOX86_LD_LIBRARY_PATH:-}" ]; then
  export BOX86_LD_LIBRARY_PATH="$WIN/box86-extracted/usr/lib/box86-i386-linux-gnu:$WIN/wine-installer/opt/wine-devel/lib:$WIN/wine-installer/opt/wine-devel/lib/wine/i386-unix"
fi
exec "$BOX86" "$WS" "$@"
